### ISSUE TITLE
Major Issue: Discord User Messages Not Displaying Content to Server Players

### ISSUE THREAD

**Issue by KernelKraze** [NikeyV1/DiscordSync#3]
Hello,

I have encountered a significant issue with the plugin. When Discord users send messages, server players can see the user names, but the message content is not displayed. This results in incomplete information being transmitted to the server players.

![asdfawheikhsd](https://github.com/user-attachments/assets/1b5a7585-80dd-413d-bc4e-19368abd2935)

![cdvrdfgdffgsdc](https://github.com/user-attachments/assets/557ef0f3-9cf5-41a7-bd41-3914cc4c7106)

Could you please investigate this issue? Your assistance in resolving this matter would be greatly appreciated.

Thank you.

Best regards,  
KernelKraze

**Comment by NikeyV1** [comment]
Are you using spigot or paper on your server?

**Comment by KernelKraze** [comment]
I am using PaperMC, with the detailed version `1.21-106-master@3a47518`

**Comment by NikeyV1** [comment]
Are you using the newest version on the mod? Can you try using version https://cdn.modrinth.com/data/7ejHaDYc/versions/S7T5R2N3/DiscordSync.jar

**Comment by KernelKraze** [comment]
Yes, there are still problems...

**Comment by NikeyV1** [comment]
Is there anything in the console? And you tried both versions?

**Comment by KernelKraze** [comment]
"The log output is:
```[02:03:57] [JDA MainWS-ReadThread/INFO]: <NickName1> ```

There are no errors, but the message output is still empty."

**Comment by NikeyV1** [comment]
And you tried both version of the plugin?

**Comment by KernelKraze** [comment]
I've been quite busy lately, but I finally identified the issue. While reviewing the Discord Bot settings, I noticed that MESSAGE CONTENT INTENT was not enabled. I apologize for any inconvenience this has caused and appreciate your patience and support.

**Comment by KernelKraze** [comment]
I've been quite busy lately, but I finally identified the issue. While reviewing the Discord Bot settings, I noticed that MESSAGE CONTENT INTENT was not enabled. I apologize for any inconvenience this has caused and appreciate your patience and support.
